"""empty message

Revision ID: 68419012cb1a
Revises: ad312964d818
Create Date: 2025-07-05 23:56:56.854755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68419012cb1a'
down_revision = 'ad312964d818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('amount_used', sa.Float(), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed_record.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_usage')
    # ### end Alembic commands ###
