"""second migration

Revision ID: ad312964d818
Revises: b8655aa06712
Create Date: 2025-07-05 22:03:32.540445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad312964d818'
down_revision = 'b8655aa06712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('batch_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('storage_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quality_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('date_purchased',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_record', schema=None) as batch_op:
        batch_op.alter_column('date_purchased',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('supplier')
        batch_op.drop_column('quality_grade')
        batch_op.drop_column('storage_location')
        batch_op.drop_column('batch_number')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
