"""Initial migration

Revision ID: b8655aa06712
Revises: 
Create Date: 2025-07-05 21:12:05.720847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8655aa06712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('administered_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_checkup', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_record', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('next_checkup')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('cost')
        batch_op.drop_column('administered_by')

    # ### end Alembic commands ###
